/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class donggua_cm_demo1ctf_JNIUtil */

#ifndef _Included_donggua_cm_demo1ctf_JNIUtil
#define _Included_donggua_cm_demo1ctf_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     donggua_cm_demo1ctf_JNIUtil
 * Method:    en
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_donggua_cm_demo1ctf_JNIUtil_en
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
